NumPy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Basic Operations

In [2]:
import numpy as np

In [5]:
a = np.array([[1,2,3]])
print(a)

[[1 2 3]]


In [4]:
type(a)

numpy.ndarray

In [10]:
a = np.array([1,2,3], dtype = str)

In [12]:
type(a)

numpy.ndarray

In [13]:
print(a)

['1' '2' '3']


In [14]:
len(a)

3

In [16]:
# 2darray
b=  np.array([[1,2,3], [5,6,7]])
print(b)

[[1 2 3]
 [5 6 7]]


In [17]:
len(b)

2

In [ ]:
a.ndim ## to check dimension of array

1

In [19]:
b.ndim

2

Why use numpy ?

In [28]:
## get a shape of numpy array
a = np.array([[1,2,3]])

In [30]:
a.shape

(1, 3)

In [23]:
b

array([[1, 2, 3],
       [5, 6, 7]])

In [24]:
b.shape

(2, 3)

In [31]:
a.dtype

dtype('int64')

Accessing/changing specific elements , rows & columns etc

In [32]:
a=  np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [33]:
a.ndim

2

In [34]:
a.shape

(2, 7)

In [36]:
## get a specific element [r,c]
print(a[0,3])

4


In [37]:
a[1,4]

np.int64(12)

In [38]:
a[1,0]

np.int64(8)

In [40]:
## get the specific roww
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [41]:
## get a specific column
a[:, 0]

array([1, 8])

In [42]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [43]:
a[0,3] = 40

In [ ]:
a ##numpy arrays are mutable in nature

array([[ 1,  2,  3, 40,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

Zeroes?Ones method in NumPy

In [45]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.zeros((3,3), dtype = 'int64')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [50]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
vara = input("Enter the value")

In [53]:
np.full((3,3), vara, dtype= 'int64')

array([[64, 64, 64],
       [64, 64, 64],
       [64, 64, 64]])

In [60]:
np.random.randint(1,100, size=(3,3)) ## range is 1 to 5 

array([[73, 56, 52],
       [45, 91, 68],
       [39, 35, 20]], dtype=int32)

In [ ]:
np.identity(5) ## to create identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
## arithematic operations
a = np.array([1,2,3,4,5])

In [71]:
a

array([1, 2, 3, 4, 5])

In [72]:
a+2

array([3, 4, 5, 6, 7])

In [73]:
a**2

array([ 1,  4,  9, 16, 25])

In [74]:
np.mean(a)

np.float64(3.0)

In [75]:
np.max(a)

np.int64(5)

In [76]:
np.min(a)

np.int64(1)